### ISSUE TITLE
CDS site's href naming scheme now includes './' prefix.

### ISSUE THREAD

**Issue by aGrimRepoMan** [PeterCDMcLean/scrape_cds_tax_breakdown#1]
The following traceback occured when running scrape_cds_tax_breakdown script this week.

--------- start of console ------------>
PS E:\Downloads> python .\scrape_cds_tax_breakdown.py --cusip 92205P104 --year 2020
Fetching
https://services.cds.ca/applications/taxforms/taxforms.nsf/./0/C78F00E7428164718525867800529AC6/$File/CDSP-BY4KMX_T3_R16_TY2020_2021_02_10_10_02_15.xls
Fetching
CDSP-BY4KMX_T3_R16_TY2020_2021_02_10_10_02_15.xls
Traceback (most recent call last):
  File ".\scrape_cds_tax_breakdown.py", line 231, in <module>
    aggregate(csv_list, args.year, args.cusip)
  File ".\scrape_cds_tax_breakdown.py", line 190, in aggregate
    wb = open_workbook(cached_xls)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\book.py", line 79, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\book.py", line 1284, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\book.py", line 1278, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<html><h'

<------ end of console ----------------

Investigation revealed that CDS site's href value for the various file download links includes a prefix of "./" (a dot character followed by a backslash character).  Example:  
`<a href="./0/C78F00E7428164718525867800529AC6/$File/CDSP-BY4KMX_T3_R16_TY2020_2021_02_10_10_02_15.xls" target="_blank"><img src="./xIcon-Excel.gif?OpenImageResource" border="0"></a>`

Consequently, the script tries to retrieve the excel file from the wrong URL. It then treats the retrieved file as an excel file, when in fact it gets back an HTML page containing an error message:
`<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 15899495736561106611</body></html>`
This is what leads to the traceback pasted above.

Presumably CDS changed their website at some point, i.e. presumably the leading "./" was recently added.

One possible fix is to change the two cusip_lookup[cusip_cell] assignments near lines 166-169 as follows:

```
			if cusip_cell in cusip_lookup:
				if (date_cell > cusip_dates[cusip_cell]):
					# OLD:  
                                        #cusip_lookup[cusip_cell] = cds_base_url + '/' + href_cell
                                        # NEW:
                                        cusip_lookup[cusip_cell] = href_cell.replace('.', cds_base_url, 1)

					cusip_dates [cusip_cell] = date_cell
			else:
                                # OLD:
				#cusip_lookup[cusip_cell] = cds_base_url + '/' + href_cell
                                # NEW:
                                cusip_lookup[cusip_cell] = href_cell.replace('.', cds_base_url, 1)

				cusip_dates [cusip_cell] = date_cell
```

**Comment by PeterCDMcLean** [comment]
Thank you, @aGrimRepoMan, for the detail analysis. I opted to just replace the /./ with / using a find/ replace. That should continue to work even if they revert to the old href path format.

What I find strange is that a browser can download a file with ./ in the path, but urllib.request.urlopen cannot.

**Comment by aGrimRepoMan** [comment]
That approach makes sense, thanks.
Also, thanks for sharing your script - it's a real "tax-time-saver".
