### ISSUE TITLE
CDS Site HTML Change causes 2021 Tax Year Fetch Failure

### ISSUE THREAD

**Issue by aGrimRepoMan** [PeterCDMcLean/scrape_cds_tax_breakdown#3]
**Problem Description:**
Fetching 2021 tax year tax slip information results in the following assertion:

(line numbers removed because was testing with modified version of your released script, modifications were unrelated to this assertion):

_Traceback (most recent call last):
  File "<redacted path>\scrape_cds_tax_breakdown.py", line xxx, in <module>
    aggregate(csv_list, args.taxyears, cusips)
  File "<redacted path>\scrape_cds_tax_breakdown.py", line yyy, in aggregate
    assert -1 not in (cusip_column, form_column, date_column)
AssertionError_

The assertion does not occur when retrieving tax years prior to 2021.

**Assessment:**
I believe CDS site HTML format changed starting with the 2021 page. It looks like the element containing the tax slip data is now the 3rd table instead of the 5th table:

_tables = soup.find_all("table")
table = tables[5]                  #  <-- This finds incorrect table starting with 2021 tax year...
rows = table.find_all("tr")
headers = rows[0].find_all("td")
cusip_column, date_column, form_column = (-1, -1, -1)
cusip_column, date_column, form_column = (-1, -1, -1)
for i in range(0, len(headers)):   # <-- so Date/Cusip/Form are incorrectly set in loop...
    if headers[i].text.strip() == "Date":
        date_column = i
    if headers[i].text.strip() == "CUSIP":
        cusip_column = i
    if headers[i].text.strip() == "Form":
        form_column = i_

...which leads to this assertion:
`assert -1 not in (cusip_column, form_column, date_column)`

**Proposal:**
Replace:

_tables = soup.find_all("table")
table = tables[5]_

With:
`        table = soup.find('table', id='taxlist')`

I tried this and it seems to work not just for 2021, but also for years going back as far as 2018.  I also spot-checked 2011 successfully.  I did not try any other years.

**Comment by PeterCDMcLean** [comment]
Thank you again, @aGrimRepoMan . I have committed your suggested modifications and my testing confirms they work as well.

**Comment by aGrimRepoMan** [comment]
Thanks for the fix, Peter.
